[package]
name = "manycore_utils"
version = "0.1.0"
edition = "2021"
authors = ["Giuseppe Barillari"]
license = "BSD-3-Clause-No-Military-License"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.197"
